### ISSUE TITLE
Create a new repository issue / subdomain issue

### ISSUE THREAD

**Issue by miguel774** [projecthydra-labs/hyku#1139]
This is probably a misconfiguration of my system.

I've installed Hyku with Docker on a brand new Ubuntu VM.

The app seems to be running fine, since I get the home page at URL http://localhost:8080/?locale=en

After I create a new repository the browser goes to this page http://test1.localhost:8080/users/sign_up?locale=en
with message: 
Server not found
Firefox can’t find the server at test1.localhost.
- Check the address for typing errors such as ww.example.com instead of www.example.com
- If you are unable to load any pages, check your computer’s network connection.
- If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by haozeng0** [comment]
Second on this.

I tried turn multitenancy off in config/settings/production.yml, and rebuild the docker, but I got solr and redis down in system status.

**Comment by jcoyne** [comment]
You have to set up DNS in the  system that hosts the docker instance.  You should be able to use `/etc/hosts`.  e.g.:

```
127.0.0.1   test1.localhost
```

If you want to wildcard the dns (e.g. `*.localhost`), you will need to set up a DNS server such as dnsmasq.

Presently there's no way to run the docker install in a single tenant mode because there is no task for creating a solr collection.   Read more at https://github.com/projecthydra-labs/hyku/wiki/Hyku-on-Docker#how-do-i-run-it-in-single-tenant-mode
