### ISSUE TITLE
Manage Groups

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#421]
Create groups, add users to groups, etc.

**Comment by ggeisler** [comment]
@hannahfrost When we next have time to review, here's a link to proposed ideas for this ticket: https://docs.google.com/document/d/1YdpD9E5p5SWRlBkmTpGUnmuX_uWbteR7NwpiuXTxx5s/edit#

**Comment by jcoyne** [comment]
I'm not sure it's possible to count files within admin sets (collections on this mockup).  Since, we don't directly associate files to admin sets and since works can be nested, and each work could have a different admin set, it's not possible to say which admin set a file belongs to.

**Comment by ggeisler** [comment]
@jcoyne Are you looking at the Manage Groups mockups linked in my message to Hannah, or at something else? I'm not sure where the file counts you're referring to are.

**Comment by jcoyne** [comment]
@ggeisler I meant to put that on #431. I'm moving it there.

**Comment by hannahfrost** [comment]
@ggeisler These look good to me. Thank you!

**Comment by ggeisler** [comment]
## Mockups

Only users in the repository administrator or repository manager roles can manage groups. First step is selecting the Manage Groups option in the admin sidebar.

![sidebar](https://cloud.githubusercontent.com/assets/101482/20360727/b32df33a-abe9-11e6-97b9-21d4b2074076.png)

### Manage Groups page

The Manage Groups option displays this page:

![manage-groups](https://cloud.githubusercontent.com/assets/101482/20360864/4700a724-abea-11e6-872c-2cdca3182357.png)

### Creating New Group

Selecting the Create New Group button at the top-right of the Manage Groups page leads here:

![new-group](https://cloud.githubusercontent.com/assets/101482/20360783/eb89b886-abe9-11e6-957f-0856d0b53586.png)

Only group name is required to create a group. Description is a new field.

Ideally, the Users and Remove tabs are disabled until the new group is saved.

### Editing a Group - Description Tab

Just enables the user to edit the group name and description.

![edit-group-description](https://cloud.githubusercontent.com/assets/101482/20360990/ca950f58-abea-11e6-83f9-cd2c4efa7e54.png)

### Editing a Group - Users Tab

This tab is used to add (or remove) users to the group. Layout is similar to the Admin Set - Participants tab. 

![edit-group-users](https://cloud.githubusercontent.com/assets/101482/20361577/f4caf326-abec-11e6-9e7a-550594ebc722.png)


### Editing a Group - Remove Tab

Since removing a group has potentially large implications, a dedicated tab for the action:

![edit-group-remove](https://cloud.githubusercontent.com/assets/101482/20361034/ece51940-abea-11e6-8065-c14071384ab8.png)

And if the Remove button is clicked, display a confirmation popup: "Are you sure you want to remove this group?"

**Comment by danhorst** [comment]
Implementation notes from standup on 2016-12-14:

- From @mjgiarlo: Because groups inherently have integration concerns this feature should be implemented in Hyku proper, not one of the underlying gems.
- From @jcoyne: Hyku is already using [rolify](https://github.com/RolifyCommunity/rolify). That gem should be able to provide the underlying datastore for group affiliation.

**Comment by danhorst** [comment]
Views now match the mockups fairly closely. Remaining tasks:
- [ ] Persist group membership
- [ ] Allow one or more members to be added to a group by ID
- [ ] Allow groups to be filtered by name or description
  - [ ] Implement behavior for clearing an applied filter
- [ ] Allow group members to be filtered by name or ID
  - [ ] Implement behavior for clearing an applied filter
- [ ] Allow users to be filtered by name or ID
- [ ] JavaScript behavior for list filter control
- [ ] JavaScript behavior for user search control
- [ ] JavaScript behavior for per-page control
- [ ] I18n all the things
- [ ] Test all the things
