### ISSUE TITLE
Default admin set

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#481]
All sites should have at least one admin set.  Change the feature flippers to "Show admin set facet?"

**Comment by ggeisler** [comment]
This seems like a fine idea. In making this change, can we do it in a way that sets us up for future features, even if they are not part of the MVP? Here's what I mean:

* Create a new menu item under Configuration > Settings called "Discovery"

![sidebar-menu](https://cloud.githubusercontent.com/assets/101482/20443862/fb8a58dc-ad8b-11e6-9203-b4f268207e4d.png)

* Create the Discovery configuration page with at least one tab, called "Facets" (the mockup below shows the other tabs that I foresee us adding in the future, assuming we want to provide configuration of search and metadata similar to Spotlight, but we could start wit just the Facets tab now). 

* Move the switch for the admin set facet to this tab. I think in this context it could just be presented as a checkbox, rather than the fancier feature flipper UI. (in the future I assume we might provide facet configuration on this page like we do in Spotlight.)

![admin-sets-facet](https://cloud.githubusercontent.com/assets/101482/20444341/efdbead0-ad8d-11e6-927d-38b91d165f8a.png)

I suppose the default state should be off (don't show admin sets unless the admin consciously decides to? Thoughts @hannahfrost?

**Comment by hannahfrost** [comment]
@ggeisler @jcoyne +1. I think this will work well.

**Comment by mjgiarlo** [comment]
@jcoyne is this in progress or should I move it back to Ready?

**Comment by jcoyne** [comment]
@mjgiarlo done as soon as we merge sufia/master ito hyrax

**Comment by mjgiarlo** [comment]
@jcoyne OK, what do you think about prioritizing that for Monday? Would be a good point for the demo.

**Comment by jcoyne** [comment]
Fixed by https://github.com/projecthydra-labs/hyrax/commit/27ad1e372c360cb2e4e4b956ee8f5ea4491dae76
