### ISSUE TITLE
Mockup: Remove brand bar (top bar) menu items

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyku#502]
As part of the goal of clearly separating administrative tasks from general use of the repository website, we can remove the top bar menu items and rely on a link in the username pull-down menu to get a logged-in user to administrative features.

We don't want to do this, however, until we have more administrative features that are easily accessible on the admin side.

## TBD

* Show how the top bar should look after removing menu items
* Finalize the look and link labels for the username pull-down menu

**Comment by hackmastera** [comment]
we just pulled those things out into the top bar. user testing from a couple of institutions with different types of users would be very informative here.

**Comment by ggeisler** [comment]
I'm not sure I understand your comment, given this is a ticket in the HyKu repo. If you're saying that you don't want to do what this ticket suggests because you recently moved the menu items in the **Sufia** codebase already, I'm not sure that's relevant from a HyKu point of view. From a HyKu point of view any previous change to the placement of menu items was a transition step towards a final design, not the final design. 

Perhaps there is some way to present the navigation differently in Sufia versus HyKu if those focused on Sufia don't like what we decide for HyKu (I'm not the one who decides whether features are implemented in Sufia or HyKu), but in this ticket my concern is design for HyKu, and being constrained by decisions made for Sufia is not, in my opinion, the proper way to design a new product.

As for user testing, from a UX perspective HyKu is extremely rough and nowhere close to being in an appropriate state for user testing.

**Comment by hackmastera** [comment]
My experience has been that hyku tickets are being implemented at all levels of the stack, so the fact that the ticket is in the hyku project is not a useful predictor of whether it will affect sufia or curation concerns. If that is a mistaken impression please let me know.

**Comment by mjgiarlo** [comment]
Thanks for the thread, @ggeisler and @hackmastera. I'm chatting with @jcoyne now about ways we can approach this more clearly. Will drop back in here later to follow up.

**Comment by hackmastera** [comment]
@ggeisler I am really just trying to give additional context.

The fact that a group of people from a diverse set of institutions with varying use cases for sufia came together and made this design decision, and that you are proposing to move the menu items back suggests that there may be good reasons to go either way here, and that it would be useful to do some user testing on it.

**Comment by mjgiarlo** [comment]
@ggeisler @hackmastera In an ideal world -- *i.e.*, one without grant deadlines! -- the Hydra-in-a-Box team would be engaging in a community-oriented process to modify the current Sufia design, but we've been challenged to do that effectively especially considering that the current Sufia design, as you've both already pointed out, has not yet been fully usability-tested. (I am super excited that [this is happening soon](https://wiki.duraspace.org/pages/viewpage.action?pageId=78159816), and eager to find ways to improve Sufia's UI based on the DURT's conclusions!)

In the meantime, given that our grant deadline is forcing the Hydra-in-a-Box team to move at a velocity that outpaces community-oriented design processes, we'll be looking to concentrate our design changes in Hyku except where there is an uncontroversial case to be made for moving something into Sufia or CC (and we'll keep looking to code review to help figure out what's uncontroversial). I think this will be valuable separation, building on the good work of the Sufia UI WG (and soon to be the DURT) to create in Hyku a concrete and accessible prototype of new design ideas for Sufia that can be easily tested for usability (in our demo instance).

@hackmastera raises a good issue about our issue management. We often do create issues in Hyku and then wind up working on them in Sufia or CC, partly because the folks creating the issues aren't always the folks whose job it is to decompose and analyze them, and so your original point/question are well taken, @hackmastera! We will work to improve at this, starting with a review of all the current Hyku tickets, making sure any that touch upon Sufia or CC have tickets in the underlying repo as well.

Thanks again for teasing this out, @ggeisler and @hackmastera!

**Comment by hannahfrost** [comment]
@ggeisler I think we can close this ticket now.

**Comment by ggeisler** [comment]
@hannahfrost Agreed.
