### ISSUE TITLE
[HyBox/production] ActiveFedora::RecordInvalid: Validation failed: Title You must provide a title

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#621]
## Backtrace

    line 69 of [PROJECT_ROOT]/app/jobs/import_work_from_purl_job.rb: process_collection
    line 40 of [PROJECT_ROOT]/app/jobs/import_work_from_purl_job.rb: process_attributes
    line 26 of [PROJECT_ROOT]/app/jobs/import_work_from_purl_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32354220)

**Comment by jcoyne** [comment]
This is due to bad collection metadata coming from PURL. Unfortunately, when this error was logged, we did not have honeybadger configured to include the parameters from ActiveJob in the context.   This should be easy to identify the problem records and remediate them if we can make it reoccur again.

**Comment by jcoyne** [comment]
Now that this is logged, we can see that the problem has to do with trying to import metadata for unpublished objects.  For example: https://argo.stanford.edu/view/druid:wm497vd0963
