### ISSUE TITLE
Review page on Admin dash should be listed under Tasks

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#634]
As an administrative user who is looking for works in a review workflow, I want to find them under the Tasks section of the admin dashboard

**Comment by jcoyne** [comment]
@hannahfrost is there a mockup that goes along with this?

**Comment by ggeisler** [comment]
I think there could be two parts to this (at least from the UX perspective): 

1. Move the Review page to go under the Tasks section heading, because this page seems to be one users will consult on a frequent basis as part of normal repository activity, not a single or infrequent configuration task, and thus users will more likely think of it as a Task rather than a Configuration action.

2. Improve the actual design of the page. I'm happy to do this but all I have to go on now is that it will include workflows with a title and a status. The current page title of "Review and comment" implies there is other content or functionality to be part of the page, but I don't really understand what it is, and I don't know how, or if it is yet possible, to get realistic data to show up on this page, so it's hard for me to speculate on how it might be improved. (This is part of the reason I asked for use cases or other documentation yesterday in ticket https://github.com/projecthydra-labs/hyrax/issues/256.)

So @hannahfrost can correct me if I'm missing something, but for now, I think for now we just want to see step 1 above done. Or we could retitle this ticket to cover both steps 1 and 2 and add a design needed ticket to it, and I can revisit when I have more information to work with.

Since the context for the menu item is changing (i.e., it won't fall under a "Workflow" heading), I'd suggest the label for the menu item and page be changed (at least for now) to "Workflows".

**Comment by mjgiarlo** [comment]
I defer to @hannahfrost on whether we want to expand this ticket to include 1 and 2.

> Since the context for the menu item is changing (i.e., it won't fall under a "Workflow" heading), I'd suggest the label for the menu item and page be changed (at least for now) to "Workflows".

Works for me.

**Comment by ggeisler** [comment]
I just noticed that @hannahfrost already created a separate ticket to address Step 2 of my earlier comment: https://github.com/projecthydra-labs/hyku/issues/635

So maybe this ticket is actionable now, and just needs to address Step 1.

**Comment by hannahfrost** [comment]
:+1: @ggeisler  this ticket is actionable for step 1. I will provide user stories for what's needed under Step 2. in #635.

**Comment by laritakr** [comment]
Completed. Hyku PR #662 and hyrax PR # 304
