### ISSUE TITLE
Mockup: Tasks > Review

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#635]
The Review UI presents a table listing of works that are in a multi-step review workflow. Columns on the table are (left to right): Title (of the work), Admin Set Title, Depositor, Submit Date, Status.

- The title of the work links to the submitted work itself where the review task is carried out
- Admin Set Title links to the Admin Set page
- Depositor links to the depositor's user profile page
- Submit Date shows a date and time, e.g., 2017-01-21 5:01pm
- Status shows the status of the item in workflow, e.g., Awaiting approval, Returned, Approved.

These columns are sortable to help a reviewer browse and sort the list of works displayed.

**Comment by hannahfrost** [comment]
@vantuyls @mjgiarlo I invite your thoughts on the contents of this ticket.

**Comment by mjgiarlo** [comment]
@hannahfrost Looks good! A few more questions, thinking about the future when there may be hundreds of such entries:

1. How many rows should the table display? And should users be allowed to alter the # of currently displayed rows (think of Blacklight's controls here)?
2. Should the table be paginated?
3. Should the table be searchable?

Thanks! This is going to be super useful.

**Comment by ggeisler** [comment]
Since we're using DataTables elsewhere in the app, can we use them for this page as well? That would enable columns to be sortable, in addition to supporting a Yes answer to the questions @mjgiarlo asks (not speaking for @hannahfrost but I do think the answer to those questions should be Yes).

**Comment by hannahfrost** [comment]
@ggeisler @mjgiarlo Answers to these questions are Yes. Let's start by displaying 20 rows? (I don't have strong feelings here). Thank you!

**Comment by ggeisler** [comment]
@hannahfrost Question related to item status: I assume that Approved would be the final and completed state of a, say, one-set review workflow. So if we were to show "Approved" as the status of an item, that implies we show items after they've completed their workflow. However, I don't think we really want to keep **all** items in the review table **forever**. I can think of a few ways to deal with this:

1. Works that have completed their workflow are immediately removed from the table. The table thus shows only works whose workflow is active, and we'd never show the status "Approved" in this table, only states that proceed Approved (or Completed, or whatever possible final states of different workflows might be).

2. Keep completed items in the table for some period, one day say, before automatically removing them. Thus we'd show the status "Approved" for completed items but only for a day (or week, whatever).

3. Show two tabs on the Workflow Review page, with one tab labelled "Active" and the other "Completed," where the Completed tab is a very similar listing to the Active tab but one that contains only items that have completed their workflow (a searchable history, basically, in case someone wants to find out when a work was approved -- though presumably that can also be done by looking at the work show page directly).

I hope this is a sensical question, though I might just not fully understand how workflows work.

**Comment by hannahfrost** [comment]
@ggeisler Makes total sense. 

I favor option 3. Access to a history of reviewed items is an outlying but plausible need. The "Completed" tab itself still may only need to display the last 20 (or whatever) items before they drop out of view (but are still dug up through a search if necessary). 

It's worth noting that sometimes a completed reviewed item may re-enter the workflow again if for some reason the approval is reversed. In this case, I'm assuming that the work would no longer be listed on the Completed tab.

Option 2 could work, but it's not ideal. I think option 1 is not acceptable.

**Comment by ggeisler** [comment]
Mockups below. There are three main pieces to this.

## Update menu item label and page title

Although the team has been using the term "workflows" when discussing this feature, from the user point of view the task relevant to this page is really about reviewing work submissions. So after discussion with @hannahfrost we suggest using "Review Submissions" as the menu label and page title.

![menu-item](https://cloud.githubusercontent.com/assets/101482/22302258/3655410e-e2eb-11e6-80c6-d0dc1c0c38c0.png)


## Under Review tab

As discussed, the mockups below include a two-tab approach, with one tabbed page showing works currently under review (i.e., works that have not completed their assigned workflows steps), and another tabbed page showing works that have completed their assigned workflow.

I assume we will show the data using DataTables, as we have elsewhere in the app, so we can easily offer searching and column-based sorting. The Under Review tab also adds a "Filter by Administrative Set" select menu, which contains a list of all administrative sets. This will help a user that is trying to understand the status of or move through the review process works associated with a specific admin set  (likely a somewhat common task, such as at the end of a semester or academic year).

The work title links to the work's show page. The depositor name links to the user profile page of the depositor. 

The default sort order of items in the table should determined by the Submission Date timestamp, DESC.

![under-review](https://cloud.githubusercontent.com/assets/101482/22302255/31f5408c-e2eb-11e6-91b5-8f6853bfd61c.png)


## Published tab

Works that have been approved and have the status of "deposited" should not be displayed on the Under Review page but should be shown on the Published page instead. The table here is very similar to the one on the Under Review tab, but instead of the Status column we should show Approval Date.

The default sort order for Items in this table should be by Approval Date, DESC.
 
(We might have to discuss the term "published" and whether it is a big deal to use that term rather than "deposited." @hannahfrost and I discussed this and both feel "published" is a clearer way to convey that an item has completed the workflow process.)

![published](https://cloud.githubusercontent.com/assets/101482/22302245/2acd60a0-e2eb-11e6-8921-9bea8ddcaca0.png)

**Comment by mjgiarlo** [comment]
Decomposed into #681 and #682. Closing. Thank you!
