### ISSUE TITLE
Admins should see non-approved works in admin/admin_sets show view

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#726]
on this page: `/admin/admin_sets/db78tc02w` Currently the unapproved work is included in the count, but not shown in the list of works.  These should be consistent.

**Comment by mjgiarlo** [comment]
@hannahfrost @ggeisler ?

My $0.02 -- I think admins should be able to see them, given what we've said/heard in other tickets: https://github.com/projecthydra-labs/hyku/issues/494 and https://github.com/projecthydra-labs/hyrax/issues/185 (I thought there was another ticket about admins having access to all works regardless of ACL, but couldn't dig it up in a pinch.)

**Comment by ggeisler** [comment]
I agree. I think admins should inherit all lower sets of privileges, so that would mean they should see any unapproved work in the repo. (This is also an assumption in the forthcoming mockups for #447.)

I was under the impression that not only could admins see all works, but they can approve and edit them as well. It might be beyond the point of this ticket, but let me know if this isn't the case so I can correct my mental model of how things work.

(**Admin Set Admins** -- which I think only exist in theory so far -- would similarly have all privileges, but only on the admin set(s) for which they are an Admin Set Admin, if my understanding of the plan is correct.)

**Comment by hannahfrost** [comment]
+1 to what @ggeisler has said.

Here is the permissions matrix that we have been working with: https://docs.google.com/spreadsheets/d/1TSZ8CUuq6puwzyJ1Av0aQ798FOQZgzhkn2jaDYyt118/edit#gid=0

You will note that on this doc we use the term "Repository Admin" and "Repository Manager". My understanding is these translate to "superadmin" and "admin" respectively as we have been referring to the roles of late.

Perhaps we need to talk about how to codify our terminology so we are confident in our communications, and also if there are tickets that need to be written (thinking of @mjgiarlo 's comment above).

**Comment by hannahfrost** [comment]
@jcoyne Is your question here resolved now?

**Comment by mjgiarlo** [comment]
Ringing @jcoyne

**Comment by jcoyne** [comment]
Yes.  Would we want any UI element to show their workflow status (e.g. published/not-published) in that list?

**Comment by mjgiarlo** [comment]
That makes sense to me, @jcoyne, and I believe an earlier mockup of @ggeisler's did have a column for that.

**Comment by ggeisler** [comment]
@jcoyne I think @mjgiarlo @hannahfrost and I all like the idea of a column ("Status"?) that shows the published state of the work, similar to the mockups in #447, something like "Published" | "In Review".

I think we want to move this ticket out of Design Needed to Ready so let us know if this doesn't answer your question.

**Comment by mjgiarlo** [comment]
@laritakr Should this issue be closed?

**Comment by laritakr** [comment]
Yes, this was implemented in Hyrax.
