### ISSUE TITLE
AdminSet visibility setting is not staying selected after save

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#744]
When I am on the  Release and Visibility tab of the Edit Admin Set screen, when I select one of the visibility options and click save, my selection is not showing on the radio button.

**Comment by hannahfrost** [comment]
@laritakr And I just found that this is true for the release options as well. Does that require a separate ticket, or can the work for this ticket apply to that fix too?

**Comment by mjgiarlo** [comment]
@hannahfrost IMO that can be part of this ticket. Is that cool, @laritakr?

**Comment by laritakr** [comment]
@mjgiarlo @hannahfrost Yes, makes sense to me.

**Comment by laritakr** [comment]
After debugging, I have found the following regarding the release options form. The radio buttons seem to function there as long as options have been correctly selected. The problem is that there is currently nothing preventing the options from being selected without the secondary options, and also nothing preventing the secondary options from being selected without the date or embargo periods.  The image below shows the combination of what is currently happening to the three involved fields and the radio buttons, and the bottom line shows what should be happening. 

This issue is being expanded to include the following tasks:

- [ ] verify that all required data is entered before allowing form to be saved

- [ ] error notification if any data is missing

<img width="648" alt="screen shot 2017-02-13 at 5 42 37 pm" src="https://cloud.githubusercontent.com/assets/17851674/22907075/5d091742-f215-11e6-81c8-2fdf4254a2b7.png">

**Comment by mjgiarlo** [comment]
Great analysis, @laritakr! Thank you.

**Comment by tdonohue** [comment]
Not sure if this helps, but this functionality was initially built for Sufia. It still works properly in Sufia (latest code as of today, I just re-verified).  But, it is definitely broken in Hyrax.  That'd imply that something in Hyrax isn't playing well with the original (Sufia-based) logic.

@laritakr : if you hit a wall, feel free to ping me. I might be able to help here, since I wrote the Sufia code. Though, nothing jumps out to me right now as the obvious source of the problem.
