### ISSUE TITLE
As an admin user, I want to see and be able to update a list of settings that I can change for my application instance and when I make a change it is immediately applied

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#8]
Could include:
- Sufia config settings
- Discovery (facets, displayed fields; see Spotlight)
- Application Appearance (UI templating)

**Comment by mjgiarlo** [comment]
Should also include metadata mappings: https://github.com/projecthydra-labs/hybox-ideas/issues/28

**Comment by ggeisler** [comment]
At this morning's standup there was some mention of starting on a design for the configuration settings. To do that, it might be useful to first collate all the settings we currently know about that we might want to include. Below is a subset of the Spotlight config settings that I think could be relevant. 

Can someone point to me a good source for understanding the current Sufia config settings, whether in the code or elsewhere? 

Also, ideas for how to break down the categories of settings (aside from 4 and 7, which are probably represented below) @jcoyne provided in projecthydra-labs/hybox-ideas#28 into more discrete pieces would be very helpful. We don't have to know everything to get started, obviously, but having some sense of the range of potential settings would help in figuring out the best way to group settings, etc.

## Spotlight Configuration Settings
### General
  - Site/app title (used in site masthead, mailers, etc.)
  - Subtitle (used in site masthead)
  - Description
  - Contact email addresses

### Application Appearance
  - Masthead image
  - Site menu config (order and labels of main menu items)

### Discovery
#### Metadata fields
  - Metadata field label editing
  - Toggle visibility of metadata fields by result view and item show page

#### Search
  - Toggle visibility of search box
  - Toggle field-based search option
  - Toggle fields shown in field-based search
  - Choose result view types to display
  - Default results per page
  - Choose sort fields to display

#### Facets
  - Toggle visibility of facets
  - Change label of facets
  - Order display of facets
  - Choose to sort facet values by frequency or value

**Comment by mjgiarlo** [comment]
@ggeisler Here's a bunch of Sufia ones, some of which are usefully commented (and others of which are not :unamused:):

https://github.com/projecthydra/sufia/blob/d515cd314a2d5e9e8179302e69824299e83e43b2/lib/generators/sufia/templates/config/sufia.rb#L2-L134

And here are CurationConcerns' (some of which are duplicative of Sufia's, but that's an unrelated refactoring opportunity for now):

https://github.com/projecthydra-labs/curation_concerns/blob/683f840397206fcb6a2028c8fa7a3c558e7b1c0a/curation_concerns-models/lib/generators/curation_concerns/models/templates/config/curation_concerns.rb#L2-L58

**Comment by ggeisler** [comment]
Thanks @mjgiarlo. Here's another list that collates settings from Spotlight, Sufia, and Curation Concerns. The groupings and grouping labels are rough; just want to have a single list of potential configuration settings for discussion purposes.

### Repository Definition
  - Site/app title (used in site masthead, mailers, etc.)
  - Subtitle (used in site masthead)
  - Description (use for SEO? otherwise maybe not needed)
  - Contact email addresses

### Repository Appearance
  - Masthead image
  - Site menu config (order and labels of main menu items)
  - Theme selection

### General Settings
  - Analytics
    - On/off
    - Analytics ID
    - Start date
  - Maximum days between audits
  - Maximum notifications for dashboard
  - Maximum days of history for User dashboard
  - Integrate with Zotero's Arkivo service?
  - Enable link to the citations page for a generic_file?
  - Display microdata?
  - Default microdata type

### Technical Settings
  - Enable ffmpeg?
  - Location of tempfiles
  - Location on local file system where derivatives will be stored
  - Location on local file system where uploaded files will be staged prior to being ingested into the repository or having derivatives generated
  - Specify the form of hostpath to be used in Endnote exports
  - NOIDs for files and collections instead of Fedora UUIDs?
  - Specify a different template for your repository's NOID IDs
  - Store identifier minter's state in a file for later replayability
  - Process for translating Fedora URIs to identifiers and vice versa
  - Specify the prefix for Redis keys
  - Specify the path to the file characterization tool
  - Sufia.fits_to_desc_mapping ?
    - file_title: :title,
    - file_author: :creator

### Roles and Permissions
  - Permission levels and labels
  - Owner permission levels and labels
  - Manage users and roles (potentially a whole set of things here)

### Discovery Settings

#### Search
  - Toggle visibility of search box
  - Toggle field-based search option
  - Toggle fields shown in field-based search
  - Choose result view types to display
  - Default results per page
  - Choose sort fields to display

#### Facets
  - Toggle visibility of facets
  - Change label of facets
  - Order display of facets
  - Choose to sort facet values by frequency or value

#### Metadata
  - Resource types label and schema
  - Metadata field label editing
  - Toggle visibility of metadata fields by result view and item show page

**Comment by mjgiarlo** [comment]
Thank you, @ggeisler! This is very helpful in my estimation.
