### ISSUE TITLE
Merge /admin/appearance from hyrax with /site/appearance

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#889]
Having a link to edit the colors would be an important first step, but having designs for an integrated page would be even better.

**Comment by atz** [comment]
Can we flesh out what this involves?  When this issue is complete:
- hyku's `app/controllers/appearances_controller.rb` is removed?
- hyrax's `app/controllers/hyrax/admin/appearances_controller.rb` absorbs the functionality from hyku?
- or is this just about design-level melding?

I'm unsure where to attack this.

**Comment by jcoyne** [comment]
@atz Gary mentioned to me at LDCX that we probably ought to have two tab panels, one for uploading an image and one for setting the colors.  The image functionality is already in hyku and the color functionality is in Hyrax.

**Comment by atz** [comment]
@jcoyne at the end both live in hyrax?

**Comment by jcoyne** [comment]
@atz No, I'm just talking about a common UI in hyku.

**Comment by jcoyne** [comment]
@mjgiarlo this is not tech debt. This is a feature we need that there is no way to reach in the UI.

**Comment by jcoyne** [comment]
Waiting on projecthydra-labs/hyrax#774

**Comment by mjgiarlo** [comment]
@jcoyne  projecthydra-labs/hyrax#774 is now merged

**Comment by jcoyne** [comment]
Now Waiting on https://github.com/projecthydra-labs/hyrax/pull/791

**Comment by mjgiarlo** [comment]
projecthydra-labs/hyrax#791 is now merged.
