### ISSUE TITLE
Not seeing 'New Work' create option

### ISSUE THREAD

**Issue by geekscruff** [projecthydra-labs/hyku#995]
### Descriptive summary

Trying out current Hyku master in single-tenant mode. Once logged in I see nothing that allows me to create a new Work. The 'share' button on the homepage disappears when I login.

Am I missing some config?

I can go direct to the /new url

**Comment by ggeisler** [comment]
I could be wrong, but I've seen this a couple of times recently and I believe it was because there was no administrative set. If you don't see any existing admin sets (Dashboard > Administrative sets), try creating one and then see if you see the Share button (and the Add work buttons on the Works page in the Administration).

You have to be logged in as an administrator to do the above.

**Comment by jcoyne** [comment]
You can also create the default admin set by running a rake task: https://github.com/projecthydra-labs/hyrax/#create-default-administrative-set

**Comment by geekscruff** [comment]
Bingo! That fixed it. I'll close the issue.
